name: zenith_html
environment:
  sdk: ">=2.0.0-dev <=2.0.0"
dependencies:
  c_builder: ^1.0.0
  tuple: ^1.0.0
  zenith:
    path: ../zenith
dev_dependencies:
  build_runner: ^0.8.0
  zenith_builder:
    path: ../zenith_builder