targets:
  image_asset:
    sources:
        - "*.png"
        - "*.jpg"
        - "*.jpeg"
        - "*.tiff"
        - "*.tga"
        - "*.psd"
        - "*.webp"
        - "*.gif"
  $default: {}
builders:
  image_asset:
    target: "zenith_builder|image_asset"
    auto_apply: root_package
    build_to: source
    import: "package:zenith_builder/zenith_builder.dart"
    builder_factories:
      - imageAssetBuilder
    build_extensions:
      .png:
        - ".png.asset.dart"
      .jpg:
        - ".jpg.asset.dart"
      .jpeg:
        - ".jpeg.asset.dart"
      .tiff:
        - ".tiff.asset.dart"
      .tga:
        - ".tga.asset.dart"
      .psd:
        - ".psd.asset.dart"
      .webp:
        - ".webp.asset.dart"
      .gif:
        - ".gif.asset.dart"